# -*- coding: utf-8 -*-
"""BringitTogether

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_khQJE28PXyUtMqTCxsocPu0IqUEtoo
"""

import pandas as pd
import openai
import json


event = "/content/EV_Buzz_dataset_Varun (4).xlsx"


df = pd.read_excel(event)


res = "/content/FINALRESULTS (2).xlsx"

dl = pd.read_excel(res)


gpt = dl["Improved GPT Results"].tolist()
gemini = dl["Improved Gemini Results"].tolist()
llama = dl["Improved Llama Results"].tolist()

event_descriptions = df["event_desc"].tolist()

import openai


import os

!pip install python-dotenv




from dotenv import load_dotenv
load_dotenv()






openai.api_key = os.getenv("OPENAI_API_KEY")
openai.api_base = "https://api.together.xyz/v1"




d2 = pd.DataFrame()


def entity_extraction(evt, evt1):
    prompt = (
    "You are given an event description: " + evt + "\n"
    "You are also given the entities extracted from that event: " + evt1 + "\n\n"
    "Your task:\n"
    "1. ONLY consider entities that are publicly traded companies. Ignore all other entities (people, governments, organizations, private companies, locations, etc.).\n"
    "2. For each public company entity, look EXACTLY at the words and phrases surrounding that company in the event description.\n"
    "   - If the language indicates a positive outcome (e.g., 'gain,' 'growth,' 'increase,' 'beat expectations'), classify as Positive.\n"
    "   - If the language indicates a negative outcome (e.g., 'loss,' 'decline,' 'drop,' 'missed expectations'), classify as Negative.\n"
    "   - If both appear, choose the stronger/more dominant meaning.\n"
    "3. Output ONLY the public companies and their sentiment. No explanations, no extra text, no other entities.\n\n"
    "Strict output format:\n\n"
    "Public Company Entity1: Positive\n"
    "Public Company Entity2: Negative\n"
    "Public Company Entity3: Positive\n"
)



    response = openai.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0
    )

    return response.choices[0].message.content.strip()



gpt_entities = []

i = 0

for event in event_descriptions:
  entities = entity_extraction(event_descriptions[i], gpt[i])
  gpt_entities.append(entities)
  i = i + 1


d2["GPT Results"] = gpt_entities



import google.generativeai as genai






API_KEY=os.getenv("GEMINI_API_KEY")
genai.configure(api_key=API_KEY)


generation_config = {"temperature": 0, "max_output_tokens": 2048}




model = genai.GenerativeModel("gemini-2.5-flash")






def entity_extraction1(evt, evt1):



  prompt = (
    "You are given an event description: " + evt + "\n"
    "You are also given the entities extracted from that event: " + evt1 + "\n\n"
    "Your task:\n"
    "1. ONLY consider entities that are publicly traded companies. Ignore all other entities (people, governments, organizations, private companies, locations, etc.).\n"
    "2. For each public company entity, look EXACTLY at the words and phrases surrounding that company in the event description.\n"
    "   - If the language indicates a positive outcome (e.g., 'gain,' 'growth,' 'increase,' 'beat expectations'), classify as Positive.\n"
    "   - If the language indicates a negative outcome (e.g., 'loss,' 'decline,' 'drop,' 'missed expectations'), classify as Negative.\n"
    "   - If both appear, choose the stronger/more dominant meaning.\n"
    "3. Output ONLY the public companies and their sentiment. No explanations, no extra text, no other entities.\n\n"
    "Strict output format:\n\n"
    "Public Company Entity1: Positive\n"
    "Public Company Entity2: Negative\n"
    "Public Company Entity3: Positive\n"
)


  response = model.generate_content(prompt, generation_config=generation_config)


  return response.text.strip()




gemini_entities = []


j = 0


for event in event_descriptions:
 entities = entity_extraction1(event_descriptions[j], gemini[j])
 gemini_entities.append(entities)
 j = j + 1




d2["Gemini Results"] = gemini_entities







import requests

api_key = os.getenv("OTHER_MODEL_API_KEY")
url = "https://api.groq.com/openai/v1/chat/completions"

headers = {
    "Authorization": f"Bearer {api_key}",
    "Content-Type": "application/json"
}


def entity_extraction2(evt, evt1):


    prompt = (
    "You are given an event description: " + evt + "\n"
    "You are also given the entities extracted from that event: " + evt1 + "\n\n"
    "Your task:\n"
    "1. ONLY consider entities that are publicly traded companies. Ignore all other entities (people, governments, organizations, private companies, locations, etc.).\n"
    "2. For each public company entity, look EXACTLY at the words and phrases surrounding that company in the event description.\n"
    "   - If the language indicates a positive outcome (e.g., 'gain,' 'growth,' 'increase,' 'beat expectations'), classify as Positive.\n"
    "   - If the language indicates a negative outcome (e.g., 'loss,' 'decline,' 'drop,' 'missed expectations'), classify as Negative.\n"
    "   - If both appear, choose the stronger/more dominant meaning.\n"
    "3. Output ONLY the public companies and their sentiment. No explanations, no extra text, no other entities.\n\n"
    "Strict output format:\n\n"
    "Public Company Entity1: Positive\n"
    "Public Company Entity2: Negative\n"
    "Public Company Entity3: Positive\n"
)




    data = {
        "model": "meta-llama/llama-4-maverick-17b-128e-instruct",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0
    }

    res = requests.post(url, headers=headers, json=data).json()
    content = res["choices"][0]["message"]["content"]

    return content.strip()


llama_entities = []



k = 0

for event in event_descriptions:
  entities = entity_extraction2(event_descriptions[k], llama[k])
  llama_entities.append(entities)
  k = k + 1


d2["Llama Results"] = llama_entities



def comparison_prompt(ent1, ent2, ent3, evt):
   prompt = (
    "You are comparing three sets of PUBLIC COMPANY SENTIMENT results from the same event.\n"
    "Each set contains companies in the format:\n"
    "    Company Name: Positive\n"
    "    Company Name: Negative\n\n"
    "Your task is to:\n"
    "    1. Normalize and standardize company names:\n"
    "        • Remove leading articles like \"the\"\n"
    "        • Normalize casing (case-insensitive)\n"
    "        • Resolve acronyms (e.g., \"IBM\" \u2192 \"International Business Machines\")\n"
    "        • Treat small wording variations as the same if they refer to the same real-world company\n"
    "          (e.g., \"Google LLC\" and \"Google\")\n\n"
    "    2. Only consider PUBLIC COMPANIES (organizations that are publicly traded or widely recognized companies).\n\n"
    "    3. Identify companies that are COMMON to all three models (GPT, GEMINI, LLAMA) AND have the SAME sentiment label across all models.\n\n"
    "    4. Identify UNIQUE companies that appear only in one model's results, regardless of sentiment.\n\n"
    "    5. If no common companies meet the criteria, return:\n"
    "       Common Companies with Same Sentiment: None\n\n"
    "Output format:\n\n"
    "Common Companies with Same Sentiment:\n"
    "    Company Name: Positive\n"
    "    Company Name: Negative\n\n"
    "Unique Companies:\n"
    "    Model Name: Company Name: Sentiment\n"
    "    Model Name: Company Name: Sentiment\n"
    "    ...\n\n"
    "Do not include explanations or extra text.\n\n"
    "Here are the results from each model:\n"
    "GPT Entities: " + ent1 + "\n"
    "GEMINI Entities: " + ent2 + "\n"
    "LLAMA Entities: " + ent3 + "\n"
    "Event Description: " + evt
)

   response = openai.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0
    )

   return response.choices[0].message.content

sum_results = []


gpt1 = d2["GPT Results"].tolist()
gpt2 = d2["Gemini Results"].tolist()
gpt3 = d2["Llama Results"].tolist()



l = 0


for l in range(198):

  sum = comparison_prompt(gpt1[l], gpt2[l], gpt3[l], event_descriptions[l])
  sum_results.append(sum)
  l = l + 1

d2["Comparing Entities "] = sum_results



file_name = "COMP.xlsx"

d2.to_excel(file_name, index=False)

