# -*- coding: utf-8 -*-
"""Comparsion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O36l4FAMOwRQFMjt4hWeREGfJq2nqzqt
"""

import pandas as pd
import json





event = "/content/entity_results2 (9).xlsx"


event1 = "/content/EV_Buzz_dataset_Varun (4).xlsx"




df = pd.read_excel(event)

dl = pd.read_excel(event1)

event_descriptions = dl["event_desc"].tolist()


entity_1 = df["entity_1"].tolist()
entity_2 = df["entity_2"].tolist()
entity_3 = df["entity_3"].tolist()


df.head()



df.head()

import openai


import os

!pip install python-dotenv





from dotenv import load_dotenv
load_dotenv()






openai.api_key = os.getenv("OPENAI_API_KEY")
openai.api_base = "https://api.together.xyz/v1"




def comparsion_prompt(ent1, ent2, ent3, evt):


    prompt = (


              "Compare the following  named entities extracted from the same event, put by different models. Your job is to identify which entities are common betweenm the models, which are unique to one or two of the entites extracted by a specific model, and provide a short summary highlighting the key differences and similarities. Ignore filler words like the, and stuff when you are finding differences. For example, if its (The AMazon Prime) vs Amazon Prime, they are estentially the same, dont make that a unique entity. Another example is The White House vs White House. If "

              "You are comparing two sets of named entities (People, Organizations, Locations) from the same row. "
    "Your job is to normalize and standardize entity names so that variations like \"The White House\" and "
    "\"White House\" are treated as the same entity (normalize casing, remove leading articles like \"the\", and "
    "resolve known acronyms like \"US\" → \"United States\", \"FBI\" → \"Federal Bureau of Investigation\"). "
    "After normalization, identify and return: (1) the list of entities common to both sets, and (2) the list of "
    "entities unique to each set. Only return the canonical (normalized) names for all outputs. Be consistent and "
    "treat case differences or minor wording differences as equivalent if they refer to the same real-world entity."


              "The output should be in the format: "


              "Unique Entities: "
              "Remmeber the unique entites are entities unique only to the specific model. For example, if GPT has an entity that LLAMA AND GEMINI BOTH DONT HAVE, ONLY THEN CAN YOU OUTPUT GPT HAVING A UNIQUE ENTITY. Dont give me a summary after just output unique entities specific to each model. I ONLY WANT THE UNIQUE ENTITIES FOR EACH SPECIFIC MODEL!  "



              "Here are the entities you have to compare: GPT Entities: " + ent1 + " GEMINI Entities: " + ent2 + " LLAMA Entities: " + ent3 + " Event Description: " + evt + "Look at all these specfific entities and output unique enties to each model that no other model has and follow guidelines above. This variable + " + ent1 + " are the entites for gpt" + ent3 + " are the entites for llama" + ent2 + " are the entites for gemini"

              "Example: "

              "Event "





    )


    response = openai.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0
    )

    return response.choices[0].message.content.strip()


sum_results = []

val = " "

ent1 = " "
ent2 = " "
ent3 = " "


for i in range(198):

  sum = comparsion_prompt(entity_1[i], entity_2[i], entity_3[i], event_descriptions[i])
  sum_results.append(sum)


df["sum_results"] = sum_results

val = df["sum_results"].tolist()




def extraction_entity(val):

  prompt = (
    "You are analyzing named entity recognition results from three language models: Gemini, GPT, and LLaMA. "
    "Each model has extracted entities from 198 events. Your task is to perform the following:\n\n"
    "1. Read through the input text'\n"
    "2. For each model (Gemini, GPT, LLaMA):\n"
    "   - Count the **total number of unique entities** extracted.\n"
    "   - List all the **unique entities** for that model. For example GPT: - Organizations: PTFI, Energy and Mineral Resources Ministry would be two entities. Look for anything that has the model(for example Gemini), and then an entity after it and count the total entities for each specific model like this\n"
    "3. Categorize each unique entity as either a **person** or an **organization**.\n\n"
    "Please return the output in the following structured format:\n"
    "- GPT: [count] unique entities and which event number it is(YOU CAN INCLUDE REPEAT ENTITIES)\n  - People: [...]\n  - Organizations: [...]\n"
    "- Gemini: [count] unique entities which event number it is(YOU CAN INCLUDE REPEAT ENTITIES\n  - People: [...]\n  - Organizations: [...]\n"
    "- LLaMA: [count] unique entities which event number it is(YOU CAN INCLUDE REPEAT ENTITIES\n  - People: [...]\n  - Organizations: [...]\n\n"
    "Here is the entity data:\n\n"
    + "\n".join(val)  # This injects your data list
)

  response = openai.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0
    )


  return response.choices[0].message.content.strip()


x = extraction_entity(val)
print(x)














file_name = "sumresults.xlsx"

df.to_excel(file_name, index=False)

