# -*- coding: utf-8 -*-
"""Comparsion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O36l4FAMOwRQFMjt4hWeREGfJq2nqzqt
"""

import pandas as pd
import json





event = "/content/entity_results2 (9).xlsx"


event1 = "/content/EV_Buzz_dataset_Varun (4).xlsx"




df = pd.read_excel(event)

dl = pd.read_excel(event1)

event_descriptions = dl["event_desc"].tolist()


entity_1 = df["entity_1"].tolist()
entity_2 = df["entity_2"].tolist()
entity_3 = df["entity_3"].tolist()


df.head()



df.head()

import openai


import os

!pip install python-dotenv





from dotenv import load_dotenv
load_dotenv()






openai.api_key = os.getenv("OPENAI_API_KEY")
openai.api_base = "https://api.together.xyz/v1"




def comparsion_prompt(ent1, ent2, ent3, evt):


    prompt = (


              "Compare the following  named entities extracted from the same event, put by different models. Your job is to identify which entities are common betweenm the models, which are unique to one or two of the entites extracted by a specific model, and provide a short summary highlighting the key differences and similarities. Ignore filler words like the, and stuff when you are finding differences. For example, if its (The AMazon Prime) vs Amazon Prime, they are estentially the same, dont make that a unique entity. Another example is The White House vs White House. If "

              "You are comparing two sets of named entities (People, Organizations, Locations) from the same row. "
    "Your job is to normalize and standardize entity names so that variations like \"The White House\" and "
    "\"White House\" are treated as the same entity (normalize casing, remove leading articles like \"the\", and "
    "resolve known acronyms like \"US\" → \"United States\", \"FBI\" → \"Federal Bureau of Investigation\"). "
    "After normalization, identify and return: (1) the list of entities common to both sets, and (2) the list of "
    "entities unique to each set. Only return the canonical (normalized) names for all outputs. Be consistent and "
    "treat case differences or minor wording differences as equivalent if they refer to the same real-world entity."


              "The output should be in the format: "

              "Common Entities: "
              "Unique Entities: "
              "Remmeber the unique entites are entities unique only to the specific model. For example, if GPT has an entity that LLAMA AND GEMINI BOTH DONT HAVE, ONLY THEN CAN YOU OUTPUT GPT HAVING A UNIQUE ENTITY"

              "Here are the entities you have to compare: GPT Entities: " + ent1 + " GEMINI Entities: " + ent2 + " LLAMA Entities: " + ent3 + " Event Description: " + evt

    )


    response = openai.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0
    )

    return response.choices[0].message.content.strip()


sum_results = []

val = " "

ent1 = " "
ent2 = " "
ent3 = " "


for i in range(198):

  sum = comparsion_prompt(entity_1[i], entity_2[i], entity_3[i], event_descriptions[i])
  sum_results.append(sum)
  val = val + "Event description: " + event_descriptions[i] + "Common and Unique Entities for these event description" + sum + "\n"
  ent1 = ent1 + entity_1[i]
  ent2 = ent2 + entity_2[i]
  ent3 = ent3 + entity_3[i]









df["sum_results"] = sum_results

def extraction_entity(val):

  prompt = (

          "You see this big blob of text. I want you to count how many unique entities each model has based on the input. There are a total of 198 events. Classify the unique entites afterwards as either people or organizations. For example, if you were to see the total unique entities for a specific event description for lets say GPT, you would keep adding them up untill you get the total unique entities for each model."

          "Here it is: " + val
  )

  response = openai.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0
    )


  return response.choices[0].message.content.strip()


x = extraction_entity(val)
print(x)







file_name = "sumresults.xlsx"

df.to_excel(file_name, index=False)

