# -*- coding: utf-8 -*-
"""Entity3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1378m9yvMkg03HUKA3jOrL0106ew6w1oa
"""

import pandas as pd
import openai
import json





event = "/content/EV_Buzz_dataset_Varun (3).xlsx"


df = pd.read_excel(event)



df.head()

event_descriptions = df["event_desc"].tolist()
event_descriptions = df["event_headline"].tolist()

df.head()





import requests
import re

import os

!pip install python-dotenv




from dotenv import load_dotenv
load_dotenv()




api_key = os.getenv("OTHER_MODEL_API_KEY")
url = "https://api.groq.com/openai/v1/chat/completions"

headers = {
    "Authorization": f"Bearer {api_key}",
    "Content-Type": "application/json"
}

def entity_extraction(text):
    prompt = (
        "Extract named entities of type People and Organizations from this event. "
        "Format as:\n"
        "People: [Alice, Bob]\n"
        "Organizations: [OpenAI, Google]\n\n"
        f"{text}"
    )

    data = {
        "model": "meta-llama/llama-4-maverick-17b-128e-instruct",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0
    }

    res = requests.post(url, headers=headers, json=data).json()
    content = res["choices"][0]["message"]["content"]

    people = re.findall(r"People:\s*\[(.*?)\]", content)
    orgs = re.findall(r"Organizations:\s*\[(.*?)\]", content)

    if people:
        p_list = people[0].split(",")
    else:
        p_list = []

    if orgs:
        o_list = orgs[0].split(",")
    else:
        o_list = []

    # Strip whitespace and join
    all_entities = [name.strip() for name in p_list + o_list]
    return ", ".join(all_entities)


final_entities = []

for event in event_descriptions:
    entities = entity_extraction(event)
    final_entities.append(entities)

df["extracted_entities"] = final_entities

filename = "2entity_results_2025_07_15.xlsx"
df.to_excel(filename, index=False)

print(final_entities[1])