# -*- coding: utf-8 -*-
"""Entity Regonition

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vTC9YappeikzPWfWKpRVZ7_Mfv37uMBx
"""

import pandas as pd
import openai
import json


event = "/content/EV_Buzz_dataset_Varun (4).xlsx"


df = pd.read_excel(event)



df.head()

event_descriptions = df["event_desc"].tolist()



df.head()

dl.head()

import openai


import os

!pip install python-dotenv




from dotenv import load_dotenv
load_dotenv()






openai.api_key = os.getenv("OPENAI_API_KEY")
openai.api_base = "https://api.together.xyz/v1"





def entity_extraction(val):
    prompt = (
    "Your job is to extract every single named entity of the types: People and Organizations. "
    "Barack Obama visited Google headquarters in 2020. Entities: People: [Barack Obama], Organizations: [Google]\n\n"
    "Read each sentence of the event carefully. Include:\n"
    "- News outlets\n"
    "- Companies\n"
    "- Government agencies\n"
    "- Airlines\n"
    "- Named individuals (first and last if available)\n\n"
    "Example:\n"
    "Event:\n"
    "Axios reported that Apple Inc. CEO Tim Cook will personally donate $1 million to President-elect Trump's inaugural committee...\n"
    "Entities:\n"
    "People: Tim Cook, Trump\n"
    "Organizations: Axios, Apple Inc\n\n"
    "Example 2:\n"
    "WSJ reported that Boeing Co. is conducting more surprise inspections at its factories as part of a broader plan to prevent manufacturing snafus like the one that led to a jet panel blowout on an Alaska Air flight a year ago. "
    "The jet maker outlined more than a dozen steps it has taken in recent months to tackle a manufacturing quality crisis that has forced Boeing to slow production and has put it under the microscope of federal regulators.\n"
    "People:\n"
    "Organizations: WSJ, Boeing Co, Alaska Air, Spirit AeroSystems, Federal Aviation Administration\n\n"
    "Now extract from the following:\n"
    f"{val}\n\n"
    "Entities:\n"
    "People:\n"
    "Organizations: Make sure you ONLY OUTPUT THE ENTITIES: PEOPLE AND ORGANIZATIONS"
)



    response = openai.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0
    )

    return response.choices[0].message.content.strip()




final_entities1 = []



for event in event_descriptions:
    entities = entity_extraction(event)
    final_entities1.append(entities)



dl = pd.DataFrame()



dl["entity_1"] = final_entities1


filename = "entity_results.xlsx"
dl.to_excel(filename, index=False)


print(final_entities1[1])