# -*- coding: utf-8 -*-
"""Entity3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1378m9yvMkg03HUKA3jOrL0106ew6w1oa
"""

import pandas as pd
import openai
import json





event = "/content/EV_Buzz_dataset_Varun (4).xlsx"


ev1 = "/content/entity_results1.xlsx"


df = pd.read_excel(event)

dl = pd.read_excel(ev1)



df.head()

event_descriptions = df["event_desc"].tolist()

dl.head()





import os



!pip install python-dotenv




from dotenv import load_dotenv
load_dotenv()





api_key = os.getenv("OTHER_MODEL_API_KEY")
url = "https://api.groq.com/openai/v1/chat/completions"

headers = {
    "Authorization": f"Bearer {api_key}",
    "Content-Type": "application/json"
}

def entity_extraction(text):
    prompt = (
        "Your job is to extract only named entities of type People and Organizations from the following event text. "
        "Do NOT explain anything or say why something is or isn't an entity. "
        "Just output:\n\n"
        "Entities:\n"


        "Example:\n"
        "Event:\n"
        "Axios reported that Apple Inc. CEO Tim Cook will personally donate $1 million to President-elect Trump's inaugural committee...\n"
        "Entities:\n"
        "People: Tim Cook, Trump\n"
        "Organizations: Axios, Apple Inc\n\n"

        f"Event:\n{text}"
    )

    data = {
        "model": "meta-llama/llama-4-maverick-17b-128e-instruct",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0
    }

    res = requests.post(url, headers=headers, json=data).json()
    content = res["choices"][0]["message"]["content"]

    return content.strip()



final_entities1 = []

for event in event_descriptions:
    entities = entity_extraction(event)
    final_entities1.append(entities)





dl["entity_3"] = final_entities1


print(len(dl))


filename = "entity_results2.xlsx"
dl.to_excel(filename, index=False)


print(final_entities1[1])


dl.head()