# -*- coding: utf-8 -*-
"""Entity2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tbWVuf3uuRnjsyqwUQMCPM5cz-Qrgu4l
"""

import pandas as pd
import openai
import json





event = "/content/EV_Buzz_dataset_Varun (4).xlsx"


ev1 = "/content/entity_results.xlsx"


df = pd.read_excel(event)

dl = pd.read_excel(ev1)



df.head()

event_descriptions = df["event_desc"].tolist()

df.head()

!pip install -q --upgrade google-generativeai

import os

!pip install python-dotenv




from dotenv import load_dotenv
load_dotenv()









import google.generativeai as genai



API_KEY=os.getenv("GEMINI_API_KEY")
genai.configure(api_key=API_KEY)

generation_config = {"temperature": 0, "max_output_tokens": 2048}


model = genai.GenerativeModel("gemini-2.5-flash")








def entity_extraction(val):
    prompt = (
        "Your job is to extract every single named entity of the types: People and Organizations. Barack Obama visited Google headquarters in 2020. Entities: People: [Barack Obama], Organizations: [Google] \n\n"
        "Read each sentence of the event carefully. Include:\n"
        "- News outlets\n"
        "- Companies\n"
        "- Government agencies\n"
        "- Airlines\n"
        "- Named individuals (first and last if available)\n\n"
        "Example:\n"
        "Event:\n"
        "Axios reported that Apple Inc. CEO Tim Cook will personally donate $1 million to President-elect Trump's inaugural committee...\n"
        "Entities:\n"
        "People: Tim Cook, Trump\n"
        "Organizations: Axios, Apple Inc\n\n"

        "Example 2: WSJ reported that Boeing Co. is conducting more surprise inspections at its factories as part of a broader plan to prevent manufacturing snafus like the one that led to a jet panel blowout on an Alaska Air flight a year ago. The jet maker outlined more than a dozen steps it has taken in recent months to tackle a manufacturing quality crisis that has forced Boeing to slow production and has put it under the microscope of federal regulators\n"
        "People"
       "Organizations, WSJ, Boeing Co, Alaska Air, Spirit AeroSystems, Federal Aviation Administration",



        "Now extract from the following:\n"
        f"{val}\n\n"
        "Entities:\n"
        "People: \n"
        "Organizations: "
    )

    response = model.generate_content(prompt, generation_config=generation_config)
    return response.text.strip()


final_entities = []



for event in event_descriptions:
    entities = entity_extraction(event)
    final_entities.append(entities)









dl["entity_2"] = final_entities


filename = "entity_results1.xlsx"
dl.to_excel(filename, index=False)






print(final_entities[1])