# -*- coding: utf-8 -*-
"""REASONING

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zHfdWuHz3NmrBQLJeswvpfqpeo_J_44Z
"""

import pandas as pd
import json





event = "/content/sumresults (10).xlsx"


event1 = "/content/EV_Buzz_dataset_Varun (4).xlsx"




df = pd.read_excel(event)

dl = pd.read_excel(event1)

event_descriptions = dl["event_desc"].tolist()


entity_1 = df["entity_1"].tolist()
entity_2 = df["entity_2"].tolist()
entity_3 = df["entity_3"].tolist()


df.head()



df.head()

import openai


import os

!pip install python-dotenv





from dotenv import load_dotenv
load_dotenv()



import requests

openai.api_key = os.getenv("OPENAI_API_KEY")
openai.api_base = "https://api.together.xyz/v1"






val = df["sum_results"].tolist()




def extraction_entity(a1,ent1, b1):

  prompt = (

             "You are given the entities extracted by GPT-4.0:\n"
    + ent1 + "\n\n"
    "You are also given the event description:\n"
    + a1 + "\n\n"
    "You are given the total unique entities extracted by GPT-4.0, LLaMA, and Gemini:\n"
    + b1 + "\n\n"
    "Instructions:\n"
    "1. CAREFULLY examine **EACH AND EVERY UNIQUE ENTITY** listed in the combined set (b1).\n"
    "2. If LLaMA or Gemini included an entity that **GPT-4.0 DID NOT** (i.e., not found in GPT-4.0’s extraction above: " + ent1 + "), explain clearly WHY you did not consider it an entity.\n"
    "3. Then, clearly state whether you would reconsider including that entity based on the other models’ extractions.\n"
    "4. If GPT-4.0 contains unique entities and NEITHER LLaMA NOR Gemini contributes any additional unique entities, reassess GPT-4.0’s entities and confirm if they are valid or should be excluded.\n\n"
    "Be direct and professional in your reasoning.\n"
    "Wrap up with a concise SUMMARY of your evaluation — MAXIMUM 4 SENTENCES.\n"
    "**DO NOT write more than 4 sentences** in your summary. "


)


  response = openai.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0
    )


  return response.choices[0].message.content.strip()



x = []


for i in range(len(val)):
  x.append(extraction_entity(event_descriptions[i], entity_1[i], val[i]))



df["gpt_reasoning"] = x




import google.generativeai as genai



API_KEY=os.getenv("GEMINI_API_KEY")
genai.configure(api_key=API_KEY)

generation_config = {"temperature": 0, "max_output_tokens": 2048}


model = genai.GenerativeModel("gemini-2.5-flash")

y = []



def extraction_entity1(a1,ent1, b1):

  prompt = (

            "You are given the entities extracted by Gemini 2.5:\n"
    + ent1 + "\n\n"
    "You are also given the event description:\n"
    + a1 + "\n\n"
    "You are given the total unique entities extracted by GPT-4.0, LLaMA, and Gemini:\n"
    + b1 + "\n\n"
    "Instructions:\n"
    "1. Thoroughly analyze **EACH AND EVERY UNIQUE ENTITY** listed in the full combined set (b1).\n"
    "2. If GPT-4.0 or LLaMA includes an entity that **Gemini 2.5 did NOT** (i.e., not found in Gemini’s extraction above: " + ent1 + "), explain clearly WHY you did not extract it as an entity.\n"
    "3. Then, clearly state whether you would reconsider including that entity based on the extractions of the other models.\n"
    "4. If Gemini 2.5 has unique entities and NEITHER GPT-4.0 NOR LLaMA has any additional unique entities, reassess Gemini’s entities and decide whether they should still be considered valid.\n\n"
    "Provide a direct and well-reasoned evaluation.\n"
    "Conclude with a precise SUMMARY — MAXIMUM 4 SENTENCES.\n"
    "**DO NOT go over 4 sentences** in the summary. "
)

  response = model.generate_content(prompt, generation_config=generation_config)
  return response.text.strip()


for i in range(len(val)):
  y.append(extraction_entity(event_descriptions[i], entity_2[i], val[i]))

df["gemin_reasoning"] = y






api_key = os.getenv("OTHER_MODEL_API_KEY")
url = "https://api.groq.com/openai/v1/chat/completions"

headers = {
    "Authorization": f"Bearer {api_key}",
    "Content-Type": "application/json"
}

import openai  # or groq, together, etc.

def entity_extraction2(a1, ent1, b1):
    prompt = (
        "You are given the entities extracted by LLaMA:\n"
    + ent1 + "\n\n"
    "You are also given the event description:\n"
    + a1 + "\n\n"
    "You are given the total unique entities extracted by GPT-4.0, LLaMA, and Gemini:\n"
    + b1 + "\n\n"
    "Instructions:\n"
    "1. CAREFULLY go through **EACH AND EVERY UNIQUE ENTITY** listed in the full set above (b1).\n"
    "2. If GPT-4.0 or Gemini includes an entity that **LLaMA does NOT** (i.e., not found in the LLaMA extraction above: " + ent1 + "), provide a clear explanation for WHY you did not consider it an entity.\n"
    "3. Then, clearly state whether you would reconsider including that entity based on the other models' extractions.\n"
    "4. If LLaMA has unique entities and NEITHER GPT-4.0 NOR Gemini has any additional unique entities, reassess LLaMA’s entities and decide whether they are truly valid or should be excluded.\n\n"
    "Be direct and professional.\n"
    "Finish with a clear, concise SUMMARY of your evaluation — MAXIMUM 4 SENTENCES.\n"
    "**DO NOT exceed 4 sentences** in your summary under any circumstances."
    )

    data = {
        "model": "meta-llama/llama-4-maverick-17b-128e-instruct",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0
    }

    res = requests.post(url, headers=headers, json=data).json()
    content = res["choices"][0]["message"]["content"]

    return content.strip()




z = []

for i in range(len(val)):
  z.append(entity_extraction2(event_descriptions[i], entity_3[i], val[i]))

df["llama_reasoning"] = z


file_name = "reasoning.xlsx"

df.to_excel(file_name, index=False)



